### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by geeky01adarsh** [thatbeautifuldream/java-dsa-bootcamp#1]
Hey hi!
Your deployment is not understandable. Kindly modify it or remove it.

**Comment by thatbeautifuldream** [comment]
What deployment?

**Comment by geeky01adarsh** [comment]
> What deployment?

The github pages you have used to showcase your project.

**Comment by thatbeautifuldream** [comment]
It's under development, on a little tight schedule, will update it in a while.

**Comment by geeky01adarsh** [comment]
> It's under development, on a little tight schedule, will update it in a while.

Sure! All the best!
