### ISSUE TITLE
Programs are not showing in lecture notes / code 

### ISSUE THREAD

**Issue by GangulyYadav** [thatbeautifuldream/java-dsa-bootcamp#30]
![image](https://user-images.githubusercontent.com/67687020/137254100-8776ffa8-528d-4a43-aea4-05b2ab2b2d72.png)

**Comment by thatbeautifuldream** [comment]
Will be proposing changes as soon as I find a little time, need to revamp the whole blog. And will push updates using same main branch.

**Comment by thatbeautifuldream** [comment]
There will be development using [Markdoc](https://markdoc.dev/) later.
