### ISSUE TITLE
Flow of program Q3 flowchart issue

### ISSUE THREAD

**Issue by Susmita-Dey** [thatbeautifuldream/java-dsa-bootcamp#54]
In the following link:-
https://github.com/thatbeautifuldream/java-dsa-bootcamp/blob/main/01-flow-of-program/q3.png 
Here the flowchart intialisation is wrong it should be i=1 instead of 0 which is correctly written in the pseudo code of the same.

**Comment by akshat-o5** [comment]
Can I work on this issue?

**Comment by thatbeautifuldream** [comment]
Yes if you can that'd be great, just send a pr

**Comment by akshat-o5** [comment]
Done, please check
