### ISSUE TITLE
If you do not want the above section, you can remove it.

### ISSUE THREAD

**Issue by Aditya664** [thatbeautifuldream/java-dsa-bootcamp#6]
## ./java-dsa-bootcamp
It looks too big and the main site is not visible 
![Screenshot_2021-09-30-11-49-06-654_com android chrome](https://user-images.githubusercontent.com/65219206/135398159-44209585-83db-4cf5-a4a2-cdd90fd16804.jpg)

**Comment by thatbeautifuldream** [comment]
the banner or the repository details ?

**Comment by Aditya664** [comment]
Look, I've removed it 
http://aditya-deshmukh.me/Mark-up-Portfolio/

**Comment by thatbeautifuldream** [comment]
please make a pr in the index.md gh-pages branch, for the same, i'll merge.

**Comment by Aditya664** [comment]
Ok I will do it

**Comment by Aditya664** [comment]
I have sent a pull request. Just put the banner image on the top it's look good.
