### ISSUE TITLE
Conditionals assignment small error

### ISSUE THREAD

**Issue by SaarthakMaini** [thatbeautifuldream/java-dsa-bootcamp#69]
In Q10 of the conditionals assignment in the answer code, you are taking the height of the parallelogram as input, it should be "side".
Simply replace "height" by "side" in the System.out.println("")  statement.

**Comment by SaarthakMaini** [comment]
Sorry it is Q5

**Comment by thatbeautifuldream** [comment]
please make a pr for the same

**Comment by SaarthakMaini** [comment]
#70 Please merge the pull request for the same. Hope I was able to give some kind of value!!
