### ISSUE TITLE
[DOCS]: Create Default Health Files

### ISSUE THREAD

**Issue by vikasganiga05** [thatbeautifuldream/java-dsa-bootcamp#73]
Every open-source author, maintainer, and contributor knows the importance of fostering a positive environment for collaboration and providing adequate resources for folks to seek help and contribute in a meaningful way. These resources include providing a Code of Conduct, a Contributing Guide, issue templates, and more. GitHub refers to this collection of documents as community health files.

- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md
- [x] Issue and pull request templates and config.yml for submitting blank issues.

To know more about default community health files visit **[Github Documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)**.

**Comment by thatbeautifuldream** [comment]
A little caught up in college exams, thank you for the input will make changes asap.

**Comment by vikasganiga05** [comment]
> A little caught up in college exams, thank you for the input will make changes asap.

Awesome! If you need any help. Please feel free to ask :slightly_smiling_face:.
