### ISSUE TITLE
Leap Year question in flow of program assignment 

### ISSUE THREAD

**Issue by SanskarJain007** [thatbeautifuldream/java-dsa-bootcamp#95]
The flowchart also mention that a year which is divisible by 400 but not divisible by 100 is also a leap year.
Something like this: - 
![image](https://user-images.githubusercontent.com/78869626/197405700-3300522f-8098-4716-974d-79b7389503bf.png)

**Comment by thatbeautifuldream** [comment]
Hey really appreciate your help in building the assignments, please raise a pull request for the same, I'll add your solution.

Thank you for your contribution

**Comment by SanskarJain007** [comment]
Actually I don't know much about PR's but I tried. Thanks though for the
opportunity.

**Comment by SanskarJain007** [comment]
Done
